#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int umeng_fb_audio_play_anim = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int umeng_fb_dialog_enter_anim = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int umeng_fb_dialog_exit_anim = 2130968578;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int umeng_fb_contact_key_array = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int umeng_fb_contact_type_array = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int umeng_fb_audo_dialog_bg = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int umeng_fb_gray = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int umeng_fb_lightblue = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int umeng_fb_line = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int umeng_fb_secondary_text_light = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int umeng_fb_white = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070001
			public const int umeng_fb_item_content_size = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int umeng_fb_item_height = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int umeng_fb_item_line_height = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int umeng_fb_item_time_size = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int umeng_fb_record_btn_text_size = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int umeng_fb_spinner_padding_left = 2131165188;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int umeng_fb_action_replay = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int umeng_fb_arrow_right = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int umeng_fb_audio_dialog_cancel = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int umeng_fb_audio_dialog_content = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int umeng_fb_audio_play_01 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int umeng_fb_audio_play_02 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int umeng_fb_audio_play_03 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int umeng_fb_audio_play_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int umeng_fb_keyboard = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int umeng_fb_plus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int umeng_fb_record = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0015
			public const int fb_reply_item_view_line = 2131361813;
			
			// aapt resource value: 0x7f0a0014
			public const int fb_reply_item_view_tag = 2131361812;
			
			// aapt resource value: 0x7f0a0006
			public const int umeng_fb_action_collapse = 2131361798;
			
			// aapt resource value: 0x7f0a0004
			public const int umeng_fb_audio_dialog_count_down_tag_tv = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int umeng_fb_audio_dialog_count_down_tv = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int umeng_fb_audio_dialog_count_tv = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int umeng_fb_audio_dialog_layout = 2131361793;
			
			// aapt resource value: 0x7f0a000f
			public const int umeng_fb_contact_spinner = 2131361807;
			
			// aapt resource value: 0x7f0a0005
			public const int umeng_fb_contact_title = 2131361797;
			
			// aapt resource value: 0x7f0a0000
			public const int umeng_fb_container = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int umeng_fb_image_detail_imageview = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int umeng_fb_input_layout = 2131361804;
			
			// aapt resource value: 0x7f0a0016
			public const int umeng_fb_keyboard_tag_btn = 2131361814;
			
			// aapt resource value: 0x7f0a0013
			public const int umeng_fb_plus_btn = 2131361811;
			
			// aapt resource value: 0x7f0a0017
			public const int umeng_fb_record_btn = 2131361815;
			
			// aapt resource value: 0x7f0a0012
			public const int umeng_fb_record_tag_btn = 2131361810;
			
			// aapt resource value: 0x7f0a001b
			public const int umeng_fb_reply_audio_duration = 2131361819;
			
			// aapt resource value: 0x7f0a0019
			public const int umeng_fb_reply_audio_layout = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int umeng_fb_reply_audio_play_anim = 2131361818;
			
			// aapt resource value: 0x7f0a001e
			public const int umeng_fb_reply_content = 2131361822;
			
			// aapt resource value: 0x7f0a0018
			public const int umeng_fb_reply_content_layout = 2131361816;
			
			// aapt resource value: 0x7f0a001c
			public const int umeng_fb_reply_date = 2131361820;
			
			// aapt resource value: 0x7f0a001f
			public const int umeng_fb_reply_image = 2131361823;
			
			// aapt resource value: 0x7f0a000e
			public const int umeng_fb_reply_item_view_line = 2131361806;
			
			// aapt resource value: 0x7f0a000d
			public const int umeng_fb_reply_item_view_tag = 2131361805;
			
			// aapt resource value: 0x7f0a000a
			public const int umeng_fb_reply_list = 2131361802;
			
			// aapt resource value: 0x7f0a001d
			public const int umeng_fb_resend = 2131361821;
			
			// aapt resource value: 0x7f0a0010
			public const int umeng_fb_send_btn = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int umeng_fb_send_content = 2131361809;
			
			// aapt resource value: 0x7f0a0008
			public const int umeng_fb_send_layout = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int umeng_fb_spinnerTarget = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int umeng_fb_swipe_container = 2131361801;
			
			// aapt resource value: 0x7f0a0020
			public const int umeng_fb_welcome_info = 2131361824;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int umeng_fb_activity_conversation = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int umeng_fb_audio_dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int umeng_fb_contact = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int umeng_fb_contact_spinner = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int umeng_fb_fragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int umeng_fb_image_dialog = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int umeng_fb_input_contact = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int umeng_fb_input_conversation = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int umeng_fb_input_conversation_audio = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int umeng_fb_reply_item_audio = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int umeng_fb_reply_item_image = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int umeng_fb_reply_item_text = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int umeng_fb_welcome_item = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int umeng_fb_back = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int umeng_fb_change_contact_title = 2131034118;
			
			// aapt resource value: 0x7f050014
			public const int umeng_fb_contact_email = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int umeng_fb_contact_info = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int umeng_fb_contact_info_hint = 2131034114;
			
			// aapt resource value: 0x7f05001a
			public const int umeng_fb_contact_key_email = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int umeng_fb_contact_key_other = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int umeng_fb_contact_key_phone = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int umeng_fb_contact_key_qq = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int umeng_fb_contact_other = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int umeng_fb_contact_phone = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int umeng_fb_contact_qq = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int umeng_fb_contact_save = 2131034126;
			
			// aapt resource value: 0x7f050022
			public const int umeng_fb_count_down = 2131034146;
			
			// aapt resource value: 0x7f05000d
			public const int umeng_fb_feedback = 2131034125;
			
			// aapt resource value: 0x7f050024
			public const int umeng_fb_no_record_permission = 2131034148;
			
			// aapt resource value: 0x7f05000c
			public const int umeng_fb_notification_content_formatter_multiple_msg = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int umeng_fb_notification_content_formatter_single_msg = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int umeng_fb_notification_ticker_text = 2131034122;
			
			// aapt resource value: 0x7f050025
			public const int umeng_fb_please_select_picture = 2131034149;
			
			// aapt resource value: 0x7f05001d
			public const int umeng_fb_press_speech = 2131034141;
			
			// aapt resource value: 0x7f050023
			public const int umeng_fb_record_fail = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int umeng_fb_record_time_short = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int umeng_fb_release_cancel = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int umeng_fb_release_send = 2131034142;
			
			// aapt resource value: 0x7f050009
			public const int umeng_fb_reply_content_default = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int umeng_fb_send = 2131034120;
			
			// aapt resource value: 0x7f050017
			public const int umeng_fb_send_fail = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int umeng_fb_sending = 2131034136;
			
			// aapt resource value: 0x7f050020
			public const int umeng_fb_slide_up_cancel = 2131034144;
			
			// aapt resource value: 0x7f050010
			public const int umeng_fb_time_minutes_ago = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int umeng_fb_time_pre_year_format = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int umeng_fb_time_right_now = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int umeng_fb_time_this_year_format = 2131034129;
			
			// aapt resource value: 0x7f050004
			public const int umeng_fb_title = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int umeng_fb_write_contact_title = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090001
			public const int umeng_fb_image_dialog_anim = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int umeng_fb_speech_dialog_style = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
